apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: todo=279425659819.dkr.ecr.eu-central-1.amazonaws.com/oron_todo
    argocd-image-updater.argoproj.io/todo.helm.image-name: app.image
    argocd-image-updater.argoproj.io/todo.helm.image-tag: app.tag
    argocd-image-updater.argoproj.io/todo.update-strategy: semver:~1.0
    #argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default
  source:
    repoURL: https://github.com/MaybeOron/todoArgo.git
    targetRevision: HEAD
    path: todo
  
    helm:
      # valueFiles:
      # - values.yaml
      
      values: |
        issuer:
          email: oronboy100@gmail.com
        app:
          image: 279425659819.dkr.ecr.eu-central-1.amazonaws.com/oron_todo
          namespace: prod
          name: todo-prod
          tag: 1.0.20
          port: 5000
          replicas: 1
          resources:
            limits:
              memory: "200Mi"
              cpu: "300m"
            requests:
              memory: "50Mi"
              cpu: "200m"
        domain:
          url: prod.oronargo.tk
        replicaCount: 1
        
  
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
   # - PruneLast=true